name: pdf_viewer_example
description: Demonstrates how to use the pdf_platform_view plugin.
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pdf_platform_view:
    path: ../

flutter:
  uses-material-design: true
